export const REPOS_REQUEST = 'REPOS_REQUEST';
export const REPOS_FAILURE = 'REPOS_FAILURE';
export const REPOS_SUCCESS = 'REPOS_SUCCESS';

export const REPO_LANGUAGES_REQUEST = 'REPO_LANGUAGES_REQUEST';
export const REPO_LANGUAGES_FAILURE = 'REPO_LANGUAGES_FAILURE';
export const REPO_LANGUAGES_SUCCESS = 'REPO_LANGUAGES_SUCCESS';
